# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spalah_Django', '0002_auto_20170830_1731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(upload_to='img'),
        ),
    ]
