# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 17:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spalah_Django', '0008_auto_20170831_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='media/'),
        ),
    ]
