# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-31 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Spalah_Django', '0010_auto_20170831_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='picture',
            field=models.FileField(blank=True, null=True, upload_to='img/'),
        ),
    ]
